# Generated by Django 3.2.5 on 2021-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='badDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.IntegerField(blank=True, null=True)),
                ('order_count', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
